---
name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: 11 06 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: make install

      - name: Update requirements
        run: make update

      - name: Make the site
        run: make build-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site